Week1 Percolation
algorithms-for-fun/algorithms-princeton-coursera pull request #2
Opened 2018-08-12 15:33 UTC by aronaks

2018-08-12 15:57 UTC, owlishDeveloper commented on Nikita/Percolation.java
> +    { return weightedSites.connected(TOP_VIRTUAL, bottomVirt); }
А что ты делаешь, когда у тебя один элемент в системе?

2018-08-12 16:56 UTC, owlishDeveloper commented on Nikita/Percolation.java
> +        validateIndex(n);
Мелочная придирка: лучше, если `validateIndex(n);` будет первым здесь

2018-08-12 18:42 UTC, owlishDeveloper commented on Nikita/Percolation.java
> +    { return weightedSites.connected(TOP_VIRTUAL, bottomVirt); }
Посмотрела внимательней на `open` и вопрос отпал

2018-08-13 20:33 UTC, owlishDeveloper requested changes
Мне понравился твой код в целом! Я увидела пару разумных решений, которые я стащу к себе (например, мне понравилась переменная fullSize в Percolation - я у себя это считаю несколько раз).

2018-08-13 20:33 UTC, owlishDeveloper commented on Nikita/Percolation.java
> +    private int numberOfOpenSites;
This is not initialized explicitly anywhere

2018-08-13 20:33 UTC, owlishDeveloper commented on Nikita/Percolation.java
> +        boolean initSiteStatus = false;
This variable is not super-essential

2018-08-13 20:33 UTC, owlishDeveloper commented on Nikita/PercolationStats.java
> +        int[] validInterval = {1, n+1};
This variable is also not really necessary (in fact, it complicates reading somewhat)

2018-08-13 20:33 UTC, owlishDeveloper commented on Nikita/PercolationStats.java
> +    public double confidenceLo()
This is a really small nit, but there's a potential of re-calculating the same value over and over again (you calculate these every time you call this method). They can be calculated in the constructor

2018-08-26 13:19 UTC, aronaks commented on Nikita/PercolationStats.java
> +    public double confidenceLo()
thank you, i've changed that

2018-10-19 04:53 UTC, merged